# Generated by Django 5.0.14 on 2026-01-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_execution', '0002_add_scenarios_and_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrun',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
