# Generated by Django 5.0.14 on 2025-12-30 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("boards", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("platform", models.CharField(help_text="Target platform (matches Board.platform)", max_length=50)),
                ("priority", models.IntegerField(default=0, help_text="Higher values are scheduled first")),
                (
                    "required_capabilities",
                    models.CharField(blank=True, help_text="Comma-separated capability names", max_length=255),
                ),
                ("status", models.CharField(choices=[("QUEUED", "QUEUED"), ("RUNNING", "RUNNING"), ("DONE", "DONE"), ("FAILED", "FAILED")], default="QUEUED", max_length=10)),
                ("timeout", models.IntegerField(default=600, help_text="Timeout in seconds")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "executed_on_board",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="boards.board"),
                ),
                (
                    "executed_on_pc",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="boards.testpc"),
                ),
            ],
            options={
                "verbose_name_plural": "TestRequests",
                "ordering": ("-priority", "created_at"),
                "indexes": [
                    models.Index(fields=["status"], name="dispatcher_status_7187c2_idx"),
                    models.Index(fields=["platform"], name="dispatcher_platform_e9a9a5_idx"),
                    models.Index(fields=["priority"], name="dispatcher_priority_965dab_idx"),
                ],
            },
        ),
    ]
