# Generated by Django 5.0.14 on 2026-01-06 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='testrequest',
            new_name='dispatcher__status_a81783_idx',
            old_name='dispatcher_status_7187c2_idx',
        ),
        migrations.RenameIndex(
            model_name='testrequest',
            new_name='dispatcher__platfor_e98aa3_idx',
            old_name='dispatcher_platform_e9a9a5_idx',
        ),
        migrations.RenameIndex(
            model_name='testrequest',
            new_name='dispatcher__priorit_58596c_idx',
            old_name='dispatcher_priority_965dab_idx',
        ),
    ]
