# Generated by Django 5.2.11 on 2026-03-07 20:06

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Capability name', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of this capability')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this capability can be used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Capabilities',
                'ordering': ('name',),
                'indexes': [models.Index(fields=['name'], name='devices_cap_name_21aafd_idx')],
            },
        ),
        migrations.CreateModel(
            name='Relay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relay_name', models.CharField(help_text='Unique name for this relay', max_length=100, unique=True)),
                ('model_type', models.CharField(choices=[('POWER_EXTENSION', 'Power Extension'), ('ETH_008_A', 'Ethernet 008 Type A'), ('ETH_008_B', 'Ethernet 008 Type B'), ('CUSTOM', 'Custom')], help_text='Type of relay', max_length=50)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('MAINTENANCE', 'Maintenance'), ('FAULT', 'Fault')], default='INACTIVE', help_text='Relay status', max_length=20)),
                ('location', models.CharField(blank=True, help_text='Physical location (e.g., Rack A, Shelf 2)', max_length=200)),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the relay', unique=True)),
                ('username', models.CharField(blank=True, help_text='Username for relay access', max_length=100)),
                ('password', models.CharField(blank=True, help_text='Password for relay access', max_length=100)),
                ('port_count', models.PositiveIntegerField(default=8, help_text='Number of ports on this relay', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this relay')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_checked_at', models.DateTimeField(blank=True, help_text='Last health check timestamp', null=True)),
            ],
            options={
                'verbose_name_plural': 'Relays',
                'ordering': ('relay_name',),
                'indexes': [models.Index(fields=['ip_address'], name='devices_rel_ip_addr_898733_idx'), models.Index(fields=['status'], name='devices_rel_status_dfe405_idx'), models.Index(fields=['relay_name'], name='devices_rel_relay_n_05beea_idx')],
            },
        ),
        migrations.CreateModel(
            name='Workstation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hostname', models.CharField(help_text='Hostname of the Workstation', max_length=255, unique=True)),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the Workstation', unique=True)),
                ('domain_name', models.CharField(blank=True, help_text='FQDN of the Workstation', max_length=255)),
                ('auth_token', models.CharField(blank=True, default='', help_text='Token used to authenticate with the Workstation', max_length=200)),
                ('workarea', models.CharField(blank=True, default='', help_text='Logical work area name/location', max_length=50)),
                ('status', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('MAINTENANCE', 'Maintenance'), ('INITIALIZING', 'Initializing')], default='OFFLINE', help_text='Workstation status', max_length=20)),
                ('os_version', models.CharField(choices=[('ubuntu_18.04', 'Ubuntu 18.04 LTS'), ('ubuntu_20.04', 'Ubuntu 20.04 LTS'), ('ubuntu_22.04', 'Ubuntu 22.04 LTS'), ('ubuntu_24.04', 'Ubuntu 24.04 LTS'), ('centos_7', 'CentOS 7'), ('centos_8', 'CentOS 8'), ('centos_9', 'CentOS 9'), ('windows', 'Windows'), ('macos', 'macOS')], default='ubuntu_22.04', help_text='Operating system version', max_length=50)),
                ('disk_mountpoint', models.CharField(default='/', help_text='Primary disk mount point', max_length=255)),
                ('location', models.CharField(blank=True, help_text='Physical location in lab/datacenter/rack', max_length=255)),
                ('cpu_utilization', models.FloatField(default=0, help_text='Current CPU load percentage')),
                ('ram_utilization', models.FloatField(default=0, help_text='Current RAM load percentage')),
                ('disk_utilization', models.FloatField(default=0, help_text='Current disk load percentage')),
                ('docker_container_count', models.PositiveIntegerField(default=0, help_text='Number of active Docker containers')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this Workstation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, help_text='Last heartbeat received from this Workstation', null=True)),
            ],
            options={
                'verbose_name': 'Workstation',
                'verbose_name_plural': 'Workstations',
                'ordering': ('hostname',),
                'indexes': [models.Index(fields=['hostname'], name='devices_wor_hostnam_6d1a8e_idx'), models.Index(fields=['ip_address'], name='devices_wor_ip_addr_8f147e_idx'), models.Index(fields=['status'], name='devices_wor_status_bf9452_idx'), models.Index(fields=['created_at'], name='devices_wor_created_52e62a_idx'), models.Index(fields=['os_version'], name='devices_wor_os_vers_944b4d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, help_text='Human readable board name', max_length=100, unique=True)),
                ('hardware_serial_number', models.CharField(help_text='Hardware serial number', max_length=100, unique=True)),
                ('project', models.CharField(help_text='Project name', max_length=50)),
                ('platform', models.CharField(choices=[('j721s2', 'TI J721S2'), ('j721e', 'TI J721E'), ('j722s', 'TI J722S'), ('j742s2', 'TI J742S2'), ('j784s4', 'TI J784S4'), ('j7200', 'TI J7200'), ('am62a', 'TI AM62A')], help_text='Platform name', max_length=50)),
                ('device_type', models.CharField(choices=[('EVM', 'EVM (Evaluation Module)'), ('HSFS', 'HSFS (High Security - Field Securable)'), ('HSSE', 'HSSE (High Security - Security Enforced)'), ('CUSTOM', 'Custom')], default='EVM', help_text='Type of device', max_length=50)),
                ('pg_version', models.CharField(blank=True, help_text='Processor SDK or software version', max_length=100)),
                ('test_farm', models.CharField(choices=[('HLOS', 'HLOS (Linux/QNX)'), ('RTOS', 'RTOS (Real-Time OS)'), ('BAREMETAL', 'Bare-metal'), ('STAGING', 'Staging'), ('INTEGRATION', 'Integration')], help_text='Test farm/environment', max_length=50)),
                ('sdk_version', models.CharField(help_text='SDK/firmware version', max_length=100)),
                ('status', models.CharField(choices=[('IDLE', 'Idle'), ('BUSY', 'Busy'), ('FLASHING', 'Flashing / Updating SDK'), ('OFFLINE', 'Offline'), ('DEACTIVATED', 'Deactivated'), ('ERROR', 'Error')], default='OFFLINE', help_text='Board status', max_length=20)),
                ('is_alive', models.BooleanField(db_index=True, default=False, help_text='Whether board is responsive')),
                ('is_locked', models.BooleanField(default=False, help_text='Whether board is locked for exclusive use')),
                ('board_ip', models.GenericIPAddressField(blank=True, help_text='IP address of the board', null=True)),
                ('relay_number', models.PositiveIntegerField(blank=True, help_text='Port number on the relay', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('location', models.CharField(blank=True, help_text='Physical location', max_length=255)),
                ('last_sdk_update_at', models.DateTimeField(blank=True, help_text='Last SDK update timestamp', null=True)),
                ('description', models.TextField(blank=True, help_text='Additional description')),
                ('notes', models.TextField(blank=True, help_text='Administrative notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Last test execution timestamp', null=True)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, help_text='Last heartbeat timestamp', null=True)),
                ('capabilities', models.ManyToManyField(blank=True, help_text='Capabilities this board supports', related_name='boards', to='devices.capability')),
                ('relay', models.ForeignKey(blank=True, help_text='Associated power/control relay', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boards', to='devices.relay')),
                ('workstation', models.ForeignKey(blank=True, help_text='Workstation that controls this board', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boards', to='devices.workstation')),
            ],
            options={
                'verbose_name': 'Board',
                'verbose_name_plural': 'Boards',
                'ordering': ('name',),
                'indexes': [models.Index(fields=['name'], name='devices_boa_name_159ee0_idx'), models.Index(fields=['hardware_serial_number'], name='devices_boa_hardwar_97a69d_idx'), models.Index(fields=['status'], name='devices_boa_status_3a03ec_idx'), models.Index(fields=['is_alive'], name='devices_boa_is_aliv_2942da_idx'), models.Index(fields=['test_farm'], name='devices_boa_test_fa_129282_idx'), models.Index(fields=['project'], name='devices_boa_project_744655_idx'), models.Index(fields=['platform'], name='devices_boa_platfor_25e6a0_idx'), models.Index(fields=['workstation'], name='devices_boa_worksta_05bb7e_idx'), models.Index(fields=['is_locked'], name='devices_boa_is_lock_95de2b_idx'), models.Index(fields=['-created_at'], name='devices_boa_created_2f1a86_idx'), models.Index(fields=['status', 'is_alive'], name='devices_boa_status_b9d0bf_idx')],
            },
        ),
    ]
