# Generated by Django 5.2.11 on 2026-03-07 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workstation',
            name='os_version',
            field=models.CharField(choices=[('ubuntu_18_04', 'Ubuntu 18.04 LTS'), ('ubuntu_20_04', 'Ubuntu 20.04 LTS'), ('ubuntu_22_04', 'Ubuntu 22.04 LTS'), ('ubuntu_24_04', 'Ubuntu 24.04 LTS'), ('centos_7', 'CentOS 7'), ('centos_8', 'CentOS 8'), ('centos_9', 'CentOS 9'), ('windows', 'Windows'), ('macos', 'macOS')], default='ubuntu_22.04', help_text='Operating system version', max_length=50),
        ),
    ]
