# Generated by Django 5.2.10 on 2026-07-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workstation',
            name='sysconn_version',
            field=models.CharField(blank=True, default='', help_text='SysConn agent version installed on this workstation', max_length=50),
        ),
    ]
