# Generated by Django 5.2.10 on 2026-07-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_add_sysconn_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='workstation',
            name='sysconn_commit',
            field=models.CharField(blank=True, default='', help_text='SysConn agent git commit hash', max_length=100),
        ),
    ]
