# Generated by Django 5.0.14 on 2025-12-28 16:58

import apps.core.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('serial_number', models.CharField(db_index=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('uart_port', models.CharField(max_length=50, validators=[apps.core.validators.validate_uart_port])),
                ('baud_rate', models.IntegerField(choices=[(9600, '9600'), (19200, '19200'), (38400, '38400'), (57600, '57600'), (115200, '115200')], default=115200)),
                ('data_bits', models.IntegerField(choices=[(7, '7'), (8, '8')], default=8)),
                ('stop_bits', models.IntegerField(choices=[(1, '1'), (2, '2')], default=1)),
                ('parity', models.CharField(choices=[('NONE', 'None'), ('EVEN', 'Even'), ('ODD', 'Odd')], default='NONE', max_length=10)),
                ('status', models.CharField(choices=[('CONNECTED', 'Connected'), ('DISCONNECTED', 'Disconnected'), ('OFFLINE', 'Offline'), ('ERROR', 'Error')], db_index=True, default='OFFLINE', max_length=20)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['serial_number'], name='boards_boar_serial__7225fa_idx'), models.Index(fields=['status'], name='boards_boar_status_2854ea_idx')],
            },
        ),
        migrations.CreateModel(
            name='BoardLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('level', models.CharField(choices=[('INFO', 'INFO'), ('WARN', 'WARN'), ('ERROR', 'ERROR')], default='INFO', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='boards.board')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BoardCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capabilities', to='boards.board')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('board', 'name')},
            },
        ),
    ]
