# Generated by Django 5.0.14 on 2025-12-30 17:00

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Capability",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Capability name", max_length=100, unique=True)),
                ("description", models.TextField(blank=True, help_text="Detailed description of this capability")),
                ("is_active", models.BooleanField(default=True, help_text="Whether this capability can be used")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Capabilities",
                "ordering": ("name",),
                "indexes": [models.Index(fields=["name"], name="boards_capa_name_1d2905_idx")],
            },
        ),
        migrations.CreateModel(
            name="Relay",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("relay_name", models.CharField(help_text="Unique name for this relay", max_length=100, unique=True)),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("POWER_EXTENSION", "Power Extension"),
                            ("ETH_008_A", "Ethernet 008 Type A"),
                            ("ETH_008_B", "Ethernet 008 Type B"),
                            ("ETH_016", "Ethernet 016"),
                            ("CUSTOM", "Custom"),
                        ],
                        help_text="Type of relay",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("MAINTENANCE", "Maintenance"),
                            ("FAULT", "Fault"),
                        ],
                        default="INACTIVE",
                        help_text="Relay status",
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(blank=True, help_text="Physical location (e.g., Rack A, Shelf 2)", max_length=200)),
                ("ip_address", models.GenericIPAddressField(help_text="IP address of the relay", unique=True)),
                (
                    "mac_address",
                    models.CharField(
                        help_text="MAC address in format XX:XX:XX:XX:XX:XX",
                        max_length=17,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid MAC address",
                                regex="^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$",
                            )
                        ],
                    ),
                ),
                (
                    "port_count",
                    models.PositiveIntegerField(
                        default=8,
                        help_text="Number of ports on this relay",
                        validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_checked_at", models.DateTimeField(blank=True, help_text="Last health check timestamp", null=True)),
            ],
            options={
                "verbose_name_plural": "Relays",
                "ordering": ("relay_name",),
                "indexes": [
                    models.Index(fields=["ip_address"], name="boards_rela_ip_addr_5c15e0_idx"),
                    models.Index(fields=["mac_address"], name="boards_rela_mac_add_6cd03e_idx"),
                    models.Index(fields=["status"], name="boards_rela_status_9d6f2f_idx"),
                    models.Index(fields=["relay_name"], name="boards_rela_relay_n_54dbd2_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="TestPC",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("hostname", models.CharField(help_text="Hostname of the PC", max_length=255, unique=True)),
                ("ip_address", models.GenericIPAddressField(help_text="IP address of the PC", unique=True)),
                ("domain_name", models.CharField(blank=True, help_text="FQDN of the PC", max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("ONLINE", "Online"), ("OFFLINE", "Offline"), ("MAINTENANCE", "Maintenance"), ("INITIALIZING", "Initializing")],
                        default="OFFLINE",
                        help_text="PC status",
                        max_length=20,
                    ),
                ),
                (
                    "os_version",
                    models.CharField(
                        choices=[
                            ("ubuntu_18_04", "Ubuntu 18.04 LTS"),
                            ("ubuntu_20_04", "Ubuntu 20.04 LTS"),
                            ("ubuntu_22_04", "Ubuntu 22.04 LTS"),
                            ("ubuntu_24_04", "Ubuntu 24.04 LTS"),
                            ("centos_7", "CentOS 7"),
                            ("centos_8", "CentOS 8"),
                            ("centos_9", "CentOS 9"),
                            ("windows_10", "Windows 10"),
                            ("windows_11", "Windows 11"),
                            ("macos_ventura", "macOS Ventura"),
                            ("macos_sonoma", "macOS Sonoma"),
                        ],
                        help_text="Operating system version",
                        max_length=50,
                    ),
                ),
                ("disk_mountpoint", models.CharField(default="/", help_text="Primary disk mount point", max_length=255)),
                ("location", models.CharField(blank=True, help_text="Physical location in lab/datacenter/rack", max_length=255)),
                ("comment", models.TextField(blank=True, help_text="Additional notes about this PC")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_heartbeat_at", models.DateTimeField(blank=True, help_text="Last heartbeat received from this PC", null=True)),
            ],
            options={
                "verbose_name": "Test PC",
                "verbose_name_plural": "Test PCs",
                "ordering": ("hostname",),
                "indexes": [
                    models.Index(fields=["hostname"], name="boards_test_hostnam_dbb754_idx"),
                    models.Index(fields=["ip_address"], name="boards_test_ip_addr_15b277_idx"),
                    models.Index(fields=["status"], name="boards_test_status_c0d548_idx"),
                    models.Index(fields=["created_at"], name="boards_test_created_722867_idx"),
                    models.Index(fields=["os_version"], name="boards_test_os_vers_0dc891_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Board",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(db_index=True, help_text="Human readable board name", max_length=100, unique=True)),
                ("hardware_serial_number", models.CharField(help_text="Hardware serial number", max_length=100, unique=True)),
                ("project", models.CharField(help_text="Project name", max_length=50)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("j721s2", "TI J721S2"),
                            ("j721e", "TI J721E"),
                            ("j722s", "TI J722S"),
                            ("j742s2", "TI J742S2"),
                            ("j784s4", "TI J784S4"),
                            ("j7200", "TI J7200"),
                            ("am62x", "TI AM62x"),
                            ("am62px", "TI AM62Px"),
                        ],
                        help_text="Platform name",
                        max_length=50,
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("EVM", "Evaluation Module"),
                            ("SOCKET_BOARD", "Socket Board"),
                            ("BREAKOUT_BOARD", "Breakout Board"),
                            ("CUSTOM", "Custom"),
                        ],
                        default="EVM",
                        help_text="Type of device",
                        max_length=50,
                    ),
                ),
                ("pg_version", models.CharField(blank=True, help_text="Processor SDK or software version", max_length=100)),
                ("execution_engine", models.CharField(blank=True, help_text="Test execution engine", max_length=100)),
                (
                    "test_farm",
                    models.CharField(
                        choices=[
                            ("HLOS", "HLOS (Linux/QNX)"),
                            ("RTOS", "RTOS (Real-Time OS)"),
                            ("BAREMETAL", "Bare-metal"),
                            ("STAGING", "Staging"),
                            ("INTEGRATION", "Integration"),
                        ],
                        help_text="Test farm/environment",
                        max_length=50,
                    ),
                ),
                ("sdk_version", models.CharField(help_text="SDK/firmware version", max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IDLE", "Idle"),
                            ("BUSY", "Busy"),
                            ("UPDATING_SDK", "Updating SDK"),
                            ("OFFLINE", "Offline"),
                            ("DEACTIVATED", "Deactivated"),
                            ("ERROR", "Error"),
                        ],
                        default="OFFLINE",
                        help_text="Board status",
                        max_length=20,
                    ),
                ),
                ("is_alive", models.BooleanField(db_index=True, default=False, help_text="Whether board is responsive")),
                ("is_locked", models.BooleanField(default=False, help_text="Whether board is locked for exclusive use")),
                ("board_ip", models.GenericIPAddressField(blank=True, help_text="IP address of the board", null=True)),
                (
                    "relay_number",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Port number on the relay",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                ("location", models.CharField(blank=True, help_text="Physical location", max_length=255)),
                ("last_sdk_update_at", models.DateTimeField(blank=True, help_text="Last SDK update timestamp", null=True)),
                ("description", models.TextField(blank=True, help_text="Additional description")),
                ("notes", models.TextField(blank=True, help_text="Administrative notes")),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="Creation timestamp")),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="Last update timestamp")),
                ("last_used_at", models.DateTimeField(blank=True, help_text="Last test execution timestamp", null=True)),
                ("last_heartbeat_at", models.DateTimeField(blank=True, help_text="Last heartbeat timestamp", null=True)),
                (
                    "capabilities",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Capabilities this board supports",
                        related_name="boards",
                        to="boards.capability",
                    ),
                ),
                (
                    "relay",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated power/control relay",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="boards",
                        to="boards.relay",
                    ),
                ),
                (
                    "test_pc",
                    models.ForeignKey(
                        blank=True,
                        help_text="TestPC that controls this board",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="boards",
                        to="boards.testpc",
                    ),
                ),
            ],
            options={
                "verbose_name": "Board",
                "verbose_name_plural": "Boards",
                "ordering": ("name",),
                "indexes": [
                    models.Index(fields=["name"], name="boards_boar_name_5ff716_idx"),
                    models.Index(fields=["hardware_serial_number"], name="boards_boar_hardwar_b3e48f_idx"),
                    models.Index(fields=["status"], name="boards_boar_status_2e775c_idx"),
                    models.Index(fields=["is_alive"], name="boards_boar_is_alive_7af2b8_idx"),
                    models.Index(fields=["test_farm"], name="boards_boar_test_fa_e6eab4_idx"),
                    models.Index(fields=["project"], name="boards_boar_project_7d8c80_idx"),
                    models.Index(fields=["platform"], name="boards_boar_platform_3d6f13_idx"),
                    models.Index(fields=["test_pc"], name="boards_boar_test_pc_e57d65_idx"),
                    models.Index(fields=["is_locked"], name="boards_boar_is_lock_3ce845_idx"),
                    models.Index(fields=["-created_at"], name="boards_boar_created_a9ba9d_idx"),
                    models.Index(fields=["status", "is_alive"], name="boards_boar_status__149a0f_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="BoardLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("message", models.TextField()),
                (
                    "level",
                    models.CharField(
                        choices=[("INFO", "INFO"), ("WARN", "WARN"), ("ERROR", "ERROR")],
                        default="INFO",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="logs", to="boards.board"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PCStats",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("HEALTHY", "Healthy"), ("WARNING", "Warning"), ("CRITICAL", "Critical"), ("UNKNOWN", "Unknown")],
                        default="UNKNOWN",
                        help_text="Overall health",
                        max_length=20,
                    ),
                ),
                ("memory_total_gb", models.FloatField(help_text="Total memory in GB", validators=[django.core.validators.MinValueValidator(0)])),
                ("memory_used_gb", models.FloatField(help_text="Used memory in GB", validators=[django.core.validators.MinValueValidator(0)])),
                ("memory_free_gb", models.FloatField(help_text="Free memory in GB", validators=[django.core.validators.MinValueValidator(0)])),
                (
                    "memory_percent",
                    models.PositiveIntegerField(
                        help_text="Memory usage percentage",
                        validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                ("disk_total_gb", models.FloatField(help_text="Total disk space in GB", validators=[django.core.validators.MinValueValidator(0)])),
                ("disk_used_gb", models.FloatField(help_text="Used disk space in GB", validators=[django.core.validators.MinValueValidator(0)])),
                ("disk_free_gb", models.FloatField(help_text="Free disk space in GB", validators=[django.core.validators.MinValueValidator(0)])),
                (
                    "disk_percent",
                    models.PositiveIntegerField(
                        help_text="Disk usage percentage",
                        validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                (
                    "cpu_percent",
                    models.FloatField(
                        help_text="CPU usage percentage",
                        validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                ("network_io_read_mb", models.FloatField(default=0, help_text="Network read in MB")),
                ("network_io_write_mb", models.FloatField(default=0, help_text="Network write in MB")),
                ("process_count", models.PositiveIntegerField(help_text="Number of active test processes")),
                ("thread_count", models.PositiveIntegerField(help_text="Number of active test threads")),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True, help_text="When this stat was recorded")),
                (
                    "test_pc",
                    models.ForeignKey(
                        help_text="Reference to the TestPC",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_stats",
                        to="boards.testpc",
                    ),
                ),
            ],
            options={
                "verbose_name": "PC Stats",
                "verbose_name_plural": "PC Stats",
                "ordering": ("-timestamp",),
                "indexes": [
                    models.Index(fields=["test_pc", "-timestamp"], name="boards_pcst_test_pc_08db29_idx"),
                    models.Index(fields=["status", "-timestamp"], name="boards_pcst_status__a8cfcc_idx"),
                    models.Index(fields=["-timestamp"], name="boards_pcst_timesta_87e066_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        check=models.Q(memory_percent__gte=0) & models.Q(memory_percent__lte=100),
                        name="memory_percent_range",
                    )
                ],
            },
        ),
    ]
