# Generated by Django 5.2.10 on 2026-02-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('boards', '0003_rename_boards_boar_name_5ff716_idx_boards_boar_name_110f36_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='assigned_boards',
            field=models.ManyToManyField(blank=True, related_name='assigned_users', through='authentication.UserBoardAssignment', through_fields=('user', 'board'), to='boards.board'),
        ),
    ]
