# Generated by Django migration for username-based authentication

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_assigned_boards'),
    ]

    operations = [
        # Add index for username field to improve authentication query performance
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='authenticat_username_idx'),
        ),
    ]
